/**
 * @file pyro_nav_hub.h
 * @brief Lightweight field-frame navigation aggregation module.
 *
 * NavHub keeps a small dead-reckoned map pose from chassis forward-solved
 * velocity feedback, accepts a target point in map coordinates, and outputs
 * chassis-frame vx/vy commands generated by the existing pyro::pid_t class.
 *
 * @author Lucky
 * @version 1.0.0
 * @date 2026-05-27
 */

#ifndef PYRO_NAV_HUB_H_
#define PYRO_NAV_HUB_H_

#include "pyro_algo_pid.h"
#include <cstdint>

namespace pyro
{

/**
 * @brief Point or vector expressed in the field/map frame.
 * 地图坐标点/向量，单位为 m。
 */
struct nav_point_t
{
    float x;
    float y;
    float z;

    nav_point_t() : x(0.0f), y(0.0f), z(0.0f)
    {
    }

    nav_point_t(const float x_, const float y_, const float z_ = 0.0f) : x(x_), y(y_), z(z_)
    {
    }
};

/**
 * @brief Attitude in radians.
 * 姿态角，单位为 rad。
 */
struct nav_attitude_t
{
    float yaw;
    float roll;
    float pitch;

    nav_attitude_t() : yaw(0.0f), roll(0.0f), pitch(0.0f)
    {
    }

    nav_attitude_t(const float yaw_, const float roll_, const float pitch_)
        : yaw(yaw_), roll(roll_), pitch(pitch_)
    {
    }
};

/**
 * @brief Current navigation output.
 * 输出速度位于当前底盘姿态坐标系下，单位为 m/s。
 */
struct nav_output_t
{
    float vx;
    float vy;
    bool arrived;
    bool target_valid;
    float distance_xy;
    nav_point_t current;
    nav_point_t target;

    nav_output_t()
        : vx(0.0f), vy(0.0f), arrived(true), target_valid(false),
          distance_xy(0.0f), current(), target()
    {
    }
};

/**
 * @brief Runtime parameters for NavHub.
 */
struct nav_hub_config_t
{
    float arrive_radius;      ///< XY 到点半径，单位 m
    float max_ground_speed;   ///< 地面投影速度限幅，单位 m/s
    float min_dt;             ///< 里程积分最小 dt，单位 s
    float max_dt;             ///< 里程积分最大 dt，单位 s
    float attitude_det_limit; ///< 姿态投影矩阵最小行列式

    nav_hub_config_t()
        : arrive_radius(0.1f), max_ground_speed(2.0f), min_dt(0.0005f),
          max_dt(0.02f), attitude_det_limit(0.05f)
    {
    }
};

/**
 * @brief Dependencies for NavHub.
 *
 * x_pid controls map-frame x error and y_pid controls map-frame y error.
 * The PID objects are owned by the caller.
 */
struct nav_hub_deps_t
{
    pid_t *x_pid;
    pid_t *y_pid;

    nav_hub_deps_t() : x_pid(nullptr), y_pid(nullptr)
    {
    }

    nav_hub_deps_t(pid_t *x_pid_, pid_t *y_pid_)
        : x_pid(x_pid_), y_pid(y_pid_)
    {
    }
};

/**
 * @brief Lightweight navigation aggregation module.
 *
 * Coordinate convention:
 * - map frame: field-fixed x/y/z, z up.
 * - chassis command frame: current chassis body x/y on the tilted robot plane.
 *
 * Attitude convention used for projection:
 * R = Rz(yaw) * Ry(pitch) * Rx(roll).
 */
class nav_hub_t
{
  public:
    nav_hub_t(const nav_point_t &initial_map_pos, const nav_hub_deps_t &deps,
              const nav_hub_config_t &config = nav_hub_config_t());

    nav_hub_t(const nav_hub_t &)            = delete;
    nav_hub_t &operator=(const nav_hub_t &) = delete;

    /**
     * @brief Reset the internal dead-reckoned map pose.
     */
    void reset(const nav_point_t &map_pos);

    /**
     * @brief Update chassis velocity feedback and attitude.
     *
     * @param vx Chassis forward-solved body-frame vx, m/s.
     * @param vy Chassis forward-solved body-frame vy, m/s.
     * @param yaw Current yaw, rad.
     * @param roll Current roll, rad.
     * @param pitch Current pitch, rad.
     */
    void update_feedback(float vx, float vy, float yaw, float roll,
                         float pitch);

    /**
     * @brief Set a map-frame XY target.
     *
     * @param target_x Target map-frame x, m.
     * @param target_y Target map-frame y, m.
     * @return true when current XY distance to target is less than
     *         config.arrive_radius, otherwise false.
     */
    bool set_target(float target_x, float target_y);

    /**
     * @brief Calculate one control step and return chassis-frame vx/vy.
     */
    nav_output_t update();

    /**
     * @brief Stop current target tracking and clear PID states.
     */
    void clear_target();

    [[nodiscard]] const nav_point_t &get_current_pos() const;
    [[nodiscard]] const nav_point_t &get_target() const;
    [[nodiscard]] const nav_attitude_t &get_attitude() const;
    [[nodiscard]] bool has_target() const;
    [[nodiscard]] float get_distance_to_target_xy() const;

    /**
     * @brief Project body-frame vx/vy onto the ground/map XY plane.
     */
    static nav_point_t body_to_ground_velocity(float body_vx, float body_vy,
                                               const nav_attitude_t &attitude);

    /**
     * @brief Convert desired ground/map XY velocity to current body-frame vx/vy.
     *
     * @return false when attitude is too close to singular.
     */
    static bool ground_to_body_velocity(float ground_vx, float ground_vy,
                                        const nav_attitude_t &attitude,
                                        float *body_vx, float *body_vy,
                                        float det_limit = 0.05f);

  private:
    [[nodiscard]] float _distance_to_target_xy(const nav_point_t &target) const;
    void _clear_pid() const;
    void _limit_ground_speed(float *vx, float *vy) const;

    nav_hub_deps_t _deps;
    nav_hub_config_t _config;
    nav_point_t _current_pos;
    nav_point_t _target;
    nav_attitude_t _attitude;
    nav_output_t _last_output;
    bool _target_valid{false};
    bool _feedback_initialized{false};
    uint32_t _dwt_cnt{0};
};

} // namespace pyro

#endif // PYRO_NAV_HUB_H_
